name: Build Android by Oktafiando
on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [12.x]
    steps:
      - name: Checkout to Action V2
        uses: actions/checkout@v2
      - name: Checkout Node JS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: |
          npm install
      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew
      - name: Build Android Release
        env:
          GOOGLE_API: ${{ secrets.GOOGLE_API }}
          WEB_CLIENT: ${{ secrets.WEB_CLIENT }}
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: webinar.apk
          path: android/app/build/outputs/apk/release/
